### ISSUE TITLE
Make contribution process clearer

### ISSUE THREAD

**Issue by barnabywalters** [microformats/tests#10]
Currently it’s quite tricky to figure out exactly where new tests should be added, and what (if anything) should be done before/after adding tests, e.g. do the mocha files need to be regenerated or something?

It would be great to have a Contributing section in the readme which outlines the process of adding new tests and making sure they’ve worked properly.

**Comment by glennjones** [comment]
Hi Barnaby

Only a couple of years to sort out your issue, but tests are now much easier to work with just a pair of HTML/JSON files and I have add a contributing section in the readme.  :)

Glenn

**Comment by barnabywalters** [comment]
Great work Glen, I love how the test suite is laid out now! It looks much, much easier to work with. I hope to replace the excellent work of tobiastom and gregor with this new version of the canonical test suite for testing php-mf2.
