### ISSUE TITLE
white space in tests

### ISSUE THREAD

**Issue by dissolve** [microformats/tests#103]
I think there are a number of tests with white space inconsistencies 
https://github.com/microformats/tests/blob/master/tests/microformats-mixed/h-entry/mixedroots.json#L19 for example should not end in a \n

**Comment by dissolve** [comment]
looks like there is already a PR for this
https://github.com/microformats/tests/pull/100/files

**Comment by jgarber623** [comment]
@dissolve Combing through issues and came across this one. Looks like #100 was merged back in August. Reasonable to close this issue out? Or, are there other files that look problematic?

**Comment by dissolve** [comment]
I did a quick look through and I think they are all good now for this issue
