### ISSUE TITLE
Implied "url" property in h-adr test with <a class="p-name u-geo">

### ISSUE THREAD

**Issue by kylewm** [microformats/tests#12]
Looking at the following test, I believe h-adr should have a "url" property with the same value as geo. 

https://github.com/microformats/tests/blob/master/h-adr.html#L140
```html
<!-- microformats example we are going to test -->
<div class="e-x-microformat">
<p class="h-adr">
    <a class="p-name u-geo" href="geo:51.526421;-0.081067;crs=wgs84;u=40">Bricklayer's Arms</a>,
    <span class="p-locality">London</span>
</p>
</div>
```

Ref: http://microformats.org/wiki/microformats-2-parsing#parsing_for_implied_properties

- if no explicit "url" property,
- then imply by:
  - if a.h-x[href] then use href for url
  - else if .h-x>a[href]:only-of-type:not[.h-*] then use that a[href] for url

**Comment by glennjones** [comment]
Fixed in last commit, will deploy to testrunner today
