### ISSUE TITLE
Invalid Test Case for Stripping Style/Script Tags

### ISSUE THREAD

**Issue by jalcine** [microformats/tests#122]
I've been working on tests for the [Rust microformats-parser][1] and I noticed that [this test case][2] includes the tags that are to be stripped from the HTML when it's been parsed. Is this the inttended result?

[1]: https://gitlab.com/maxburon/microformats-parser/-/merge_requests/1
[2]: https://github.com/microformats/tests/blob/master/tests/microformats-v2/h-entry/scriptstyletags.json

**Comment by sknebel** [comment]
Fairly clearly an outdated test - the rules to remove these were as far as I remember added later.

**Comment by Zegnat** [comment]
I think that test case is correct. What are we expecting?

The `html` member of the object should contain whatever [`innerHTML`](https://w3c.github.io/DOM-Parsing/#the-innerhtml-mixin) returns, which includes all tags including `<script>` and `<style>`.

**Comment by sknebel** [comment]
derp, @Zegnat is correct. I shouldn't microformat before the second coffee. (and mentally confused it with `<template>` tags...)

**Comment by jalcine** [comment]
I don't see where this is permitted at https://microformats.org/wiki/microformats2-parsing#parsing_an_e-_property

**Comment by sknebel** [comment]
Other way around: where does the parsing spec require filtering these tags out?

**Comment by dissolve** [comment]
it says to parse it via the serializing HTML fragments algo
https://html.spec.whatwg.org/multipage/parsing.html#serialising-html-fragments
From my quick reading of it, we would be required to include the tags.

**Comment by jalcine** [comment]
Gotcha. Thanks y'all.

For those reading in the (far) future: I mistook `value`'s parsing rules for `html`. `html` is permitted to keep some tags where as `value` should be stripped of them.
