### ISSUE TITLE
h-entry test 'Entry with summary and content'  has summary nested in content

### ISSUE THREAD

**Issue by grantmacken** [microformats/tests#14]
https://github.com/microformats/tests/blob/master/h-entry.html
https://github.com/microformats/tests/blob/master/mocha-tests/h-entry-test.js

test: Entry with summary and content
the output result does not include a summary property
note: the p-summary is nested in e-content.  

pasted  'Entry with summary and content'' markup into
http://waterpigs.co.uk/php-mf2
and output includes summary.
it flattened summary property as a child of a entry.  (not a child of content )
I think this is what should happen as properties are flattened under a root mf

**Comment by glennjones** [comment]
Hi Grant

So I had a quick look at summary test http://testrunner-47055.onmodulus.net/test/microformats-v2/h-entry/summarycontent/ The test is correct a number of people use the first <p> of their content to create a summary.

php-mf2 is adding the summary to the output http://testrunner-47055.onmodulus.net/run/php-mf2/microformats-v2/h-entry/summarycontent/  Its failing the test only on the very new rel-urls property thats missing and that its text handling is more advanced than the current spec.

Hope that answers your issue, if not please feel free to open it again.
