### ISSUE TITLE
h-card test has duplicate nested property on top-level

### ISSUE THREAD

**Issue by barnabywalters** [microformats/tests#15]
https://github.com/microformats/tests/blob/master/h-card.html#L212

The p-org h-card turns up twice in the JSON, once in the correct nested place, and once in the top-level items list. This is inconsistent with the parsing spec, which dictates that nested microformats should just be nested as per http://microformats.org/wiki/microformats2-parsing#parse_an_element_for_class_microformats

cc @tobiastom

**Comment by glennjones** [comment]
Hi Barnaby

Yes this error was in a number of tests. I have now gone through them all and corrected the issue.

cc @tobiastom
