### ISSUE TITLE
the new rel-urls key is making mf2py fail all the tests

### ISSUE THREAD

**Issue by kevinmarks** [microformats/tests#16]
Should I add it to the results and send a pull request?

http://testrunner-47055.onmodulus.net/run/mf2py/all/

background: http://microformats.org/wiki/microformats2-parsing-brainstorming#more_information_for_rel-based_formats

**Comment by glennjones** [comment]
Hi Kevin

I am not sure if it should be part of the main microformat-v2 tests group at the moment. 

I consider anything that makes onto parsing rules page http://microformats.org/wiki/microformats2-parsing to be the strict structure of output. Once its talked through with community and its gets agreement to be move from brainstorming to parsing rules, then fine it should be in there. 

For now we could add it as experimental group to the tests. i.e. a new directory in 'tests' call experimental with pairs of HTML and JSON files for each test.

pull-request with test would help. If its a new test group can you also add a change-log.html file along the line of whats already there. I am going to write up a little guide for contribution soon.

I will also look at way of allow parsers to support new experimental top level structures without all the tests throwing errors

**Comment by tantek** [comment]
Noting this issue on the brainstorming doc - so I can resolve it once I've made the edit to microformats2-parsing.

**Comment by glennjones** [comment]
Tantek moved rel-urls into the parser instruction and out of brainstorming, so they are in the latests tests
