### ISSUE TITLE
Whitespace collapsing

### ISSUE THREAD

**Issue by andyleap** [microformats/tests#17]
In microformats-v2/h-adr/geo and other similar tests, the label property has it's whitespace collapsed, which is contrary to the microformats parsing rules, see: 
http://microformats.org/wiki/microformats2-parsing-issues#When_to_collapse_whitespace_in_properties

and:
http://www.w3.org/TR/DOM-Level-3-Core/core.html#Node3-textContent, specifically: `No whitespace normalization is performed`

**Comment by glennjones** [comment]
Hi Andy

You where right, no whitespace normalisation should be performed. I have updated all the test to match the spec. Even built a little tool to check how the browsers do it. http://testrunner-47055.onmodulus.net/textcontent/

To get my parsers work correctly with this element of the spec I moved the "whitespace normalisation" feature under an experimental option which is off by default. I think flagged new/experimental features  is better than the concept of a "strict" mode. I copy idea from browsers.

You can see example of experimental options at http://glennjones.net/tools/microformats/
