### ISSUE TITLE
relative URLs in html; absolute URLs in json

### ISSUE THREAD

**Issue by kevinmarks** [microformats/tests#18]
Many of the tests use relative URLs in the html, but have absolute URLs in the json result. Without a base declaration these are spurious.

Should we make them absolute in the html, or relative in the json?

examples:
/microformats2/rel=alternate
has 
&lt;link rel="updates alternate" type="application/atom+xml" href="updates.atom" /&gt;
become 
{
    "items": [],
    "rels": {},
    "alternates": [{
        "url": "http://tantek.com/updates.atom",
        "type": "application/atom+xml",
        "rel": "updates"
    }]
}

**Comment by kevinmarks** [comment]
fixing the html would mean it becomes:

<base href="http://tantek.com"><link rel="updates alternate" type="application/atom+xml" href="updates.atom" />

alternatively, fixing the json would make it:

{
"items": [],
"rels": {},
"alternates": [{
"url": "updates.atom",
"type": "application/atom+xml",
"rel": "updates"
}]
}

**Comment by andyleap** [comment]
I'm not sure these are actually spurious.  Parsers should be able to normalize urls based off of the url of the parsed content.  Issue is more likely that a specific parser doesn't accept a baseurl parameter for testing.

**Comment by tantek** [comment]
@kevinmarks "relative in the json" is never acceptable since the necessary context to determine the absolute URL has been lost by then.

**Comment by glennjones** [comment]
The parser should always try resolve URLs. This issue has been deal with by passing baseurl to parser interface for testing
