### ISSUE TITLE
implying url property from grandchild elements

### ISSUE THREAD

**Issue by willnorris** [microformats/tests#50]
The `microformats-v2/h-card/impliedname` test [includes the following case](https://github.com/microformats/tests/blob/17d31dbeb3d64426d5a15548ea778f61df73c28f/tests/microformats-v2/h-card/impliedname.html#L11):

```html
<div class="h-card"><span><area href="jane.html" alt="Jane Doe"></area></span></div>
```

The expected value [is listed as](https://github.com/microformats/tests/blob/17d31dbeb3d64426d5a15548ea778f61df73c28f/tests/microformats-v2/h-card/impliedname.json#L49-L55):

```json
{
  "type": ["h-card"],
  "properties": {
    "name": ["Jane Doe"],
    "url": ["http://example.com/jane.html"]
  }
}
```

So the url property is being implied by the `area[href]` attribute.  However [the parsing spec](http://microformats.org/wiki/microformats2-parsing#parsing_for_implied_properties) doesn't mention descending into grandchild elements for implying url properties.  It does mention this for both name and photo properties, but not url.  So I'm not sure if this is actually an error in the spec or in the tests, but they certainly don't agree.

For comparison, microformat-node (and probably microformatshiv?) seems to be the only library implying the url property in this case: http://willnorris.net/mf2compare/?url=https://willnorris.com/tmp/uf/impliedname-8.html

/cc @tantek @glennjones

**Comment by willnorris** [comment]
Proposal to update spec to include the following at the end of implied url parsing rules:

- else if .h-x>:only-child>a[href]:only-of-type:not[.h-*] then use that [href] for url
- else if .h-x>:only-child>area[href]:only-of-type:not[.h-*] then use that [href] for url

these are identical to the existing rules with the addition of the `:only-child` selector.

**Comment by gRegorLove** [comment]
Accepted 2016-06-05 at IndieWeb Summit. Spec updated 2016-06-11.

**Comment by willnorris** [comment]
Closing as fixed.
