### ISSUE TITLE
value property on nested microformat

### ISSUE THREAD

**Issue by willnorris** [microformats/tests#51]
The `microformats-v2/h-card/impliedname` test [includes the following case](https://github.com/microformats/tests/blob/17d31dbeb3d64426d5a15548ea778f61df73c28f/tests/microformats-v2/h-card/impliedname.html#L15):

``` html
<div class="h-card"><span class="h-card"><img src="john.html" alt="John Doe"/>Name</span></div>
```

The expected value [is listed as](https://github.com/microformats/tests/blob/17d31dbeb3d64426d5a15548ea778f61df73c28f/tests/microformats-v2/h-card/impliedname.json#L75-L88):

``` json
{
  "type": ["h-card"],
  "properties": {
    "name": ["Name"]
  },
  "children": [{
    "value": "Name",
    "type": ["h-card"],
    "properties": {
      "name": ["John Doe"],
      "photo": ["http://example.com/john.html"]
    }
  }]
}
```

I don't think the child h-card should have a "value" field.  The only two cases that the [parsing spec](http://microformats.org/wiki/microformats2-parsing) talks about having a "value" field is for an e-\* property, or when the child microformat is itself a property of the parent.  But since the `<span>` in this example only has the "h-card" class, this doesn't seem to apply.

This same thing may be happening in other tests within the suite, I don't know... this is just the first I came across.

For comparison, here's how the common libraries handle this:
http://willnorris.net/mf2compare/?url=https://willnorris.com/tmp/uf/impliedname-11.html

Then again, all of them are incorrectly applying the name and photo to the outer h-card, so maybe not the best example :)

**Comment by tantek** [comment]
"value" on an item in the "children" array looks like a bug in the test case. The only instance in the parser spec that generates a "value", for when:
"child element itself has a microformat ("h-*" or backcompat roots) **and** is a property element"
**Emphasis** added.
and in the "child microformat is a property element" case, that child goes on the property's array of values, and NOT in the "children" array (which is only for the "else" clause).
