### ISSUE TITLE
Fix tests that parse "value" for nested microformat when not a property

### ISSUE THREAD

**Issue by gRegorLove** [microformats/tests#58]
`value` should only be parsed for nested microformats when they also have a property class. Multiple tests have a `value` in the expected output when they shouldn't.

* https://github.com/microformats/tests/blob/master/tests/microformats-v2/h-card/nested.json
* https://github.com/microformats/tests/blob/master/tests/microformats-v2/h-card/impliedurl.json
* https://github.com/microformats/tests/blob/master/tests/microformats-v2/h-card/impliedphoto.json
* ...

Please comment with others as they're discovered.

mf2py parses correctly:
```
{
    "rels": {}, 
    "items": [
        {
            "type": [
                "h-card"
            ], 
            "properties": {
                "url": [
                    "http://blog.lizardwrangler.com/"
                ], 
                "name": [
                    "Mitchell Baker"
                ]
            }, 
            "children": [
                {
                    "type": [
                        "h-org", 
                        "h-card"
                    ], 
                    "properties": {
                        "url": [
                            "http://mozilla.org/"
                        ], 
                        "name": [
                            "Mozilla Foundation"
                        ]
                    }
                }
            ]
        }
    ], 
    "rel-urls": {}
}
```

Reference:
http://microformats.org/wiki/microformats2-parsing##if+that+child+element+itself+has+a+microformat
php-mf2 issue: https://github.com/indieweb/php-mf2/issues/98
mf2py resolved issue: https://github.com/indieweb/php-mf2/issues/99

**Comment by gRegorLove** [comment]
Similar issue previously fixed: https://github.com/microformats/tests/pull/53

**Comment by dissolve** [comment]
I think these are all fixed now https://github.com/microformats/tests/commit/59cabf19228472deb4be46ddd9432a64185b7b01#diff-f21c1ccd7a418443c9debd5c772701a7

**Comment by gRegorLove** [comment]
Resolved per above.
