### ISSUE TITLE
incorrectly using value-class-pattern for email address

### ISSUE THREAD

**Issue by dissolve** [microformats/tests#65]
https://github.com/microformats/tests/blob/master/tests/microformats-v1/hcard/email.html

the spec says that

"The value class pattern only applies to properties which are simple strings, enumerated values, telephone numbers, and datetimes. The value class pattern does not affect parsing of properties of type email, URL, URI, UID."

its pretty clearly a logic error in the test too since the correct parsing would yield an email field of notthis@example.com

**Comment by tantek** [comment]
Sure looks like it. I wonder @glennjones has an opinion. I don't know of anyone using "type" with email in the wild. I would drop this test.

**Comment by gRegorLove** [comment]
Confirmed the Python parser correctly gets `notthis@example.com`. I'm switching the order of the email addresses in that snippet so the expected result is `john@example.com`
