### ISSUE TITLE
Release package on packagist.org

### ISSUE THREAD

**Issue by aaronpk** [microformats/tests#76]
Now that php-mf2 pulls in the tests as a dev dependency, this needs to be released on packagist.org so people can still install php-mf2 from packagist. I'm happy to take this on.

**Comment by aaronpk** [comment]
I think this should be called `mf2/tests` on packagist so that it shows up here: https://packagist.org/packages/mf2/

**Comment by pfefferle** [comment]
I this the correct homepage `https://github.com/aaronpk/p3k-http`?

**Comment by aaronpk** [comment]
wow i'm not sure how that snuck in

**Comment by jkphl** [comment]
@aaronpk Any plans on when you're going to release this (on packagist)? Right now several of my packages are broken (as well as php-mf2) and [can't be installed / tested anymore](https://travis-ci.org/jkphl/micrometa/jobs/236518948). Thanks!

**Comment by aaronpk** [comment]
I'm waiting for @barnabywalters to add me as a maintainer on the packagist org so that I can submit it. As soon as he does, I'll add it and fix php-mf2!

**Comment by jkphl** [comment]
So I guess it's time to call it a day now ;)

**Comment by jgarber623** [comment]
Combing through issues and came across this one…

Packagist is reporting [this package](https://packagist.org/packages/mf2/tests) is abandoned. I'm guessing that's not the case, but I'm not familiar enough with Packagist to know what the issue might be.

@aaronpk Is that related to your note from 26 May 2017 (re: being added as a maintainer)…?

**Comment by gRegorLove** [comment]
Un-abandoned [now](https://chat.indieweb.org/microformats/2018-08-07#t1533666663859900).
