### ISSUE TITLE
Remove no longer relevant tests

### ISSUE THREAD

**Issue by cleverdevil** [microformats/tests#82]
The following sets of tests are not representative of the current state of mf2 in spec or practice, as `h-news`, `h-as-*`, and `h-org` are basically not a thing.

* `tests/microformats-v2/h-card/horghcard.json`
* `tests/microformats-v2/h-as-note`
* `tests/microformats-v2/h-news`
* `tests/microformats-v2/h-org`

Suggest removing these tests entirely.

**Comment by gRegorLove** [comment]
Related: #57

**Comment by gRegorLove** [comment]
Resolved with #84. This issue can be closed.
