### ISSUE TITLE
JSON should always include "rels" hash, even when empty

### ISSUE THREAD

**Issue by jlsuttles** [microformats/tests#9]
According to the [microformats2 parsing specification](http://microformats.org/wiki/microformats2-parsing#parse_a_document_for_microformats)

> To parse a document for microformats:

> start with an empty JSON "items" array and "rels" hash:
```js
{
 "items": [],
 "rels": {}
}
```

**Comment by glennjones** [comment]
The latest tests have been rewritten to current parsing page instructions on wiki and include rels={}
